<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class ProductMasterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $productMasterData = [
            [
                'product_code' => 'OWC',
                'product_name' => 'Web Connect Lite',
                'product_category' => 'Web Connect',
                'product_tag' => json_encode(['web_connect']),
                'bundle_id' => null,
                'image' => 'web_connect_lite.svg',
                'place_type' => 'residential',
                'has_subscription' => 0,
                'content_for_plan' => '<ul><li>Month-to-Month</li><li>UNLIMITED Data</li><li>Free Installation</li><li>Free WIFI-enabled ONT</li></ul>',
                'download_speed' => 20,
                'upload_speed' => 10,
                'contract_period' => 'Month-to-Month',
                'price_PM' => 349.00,
                'compare_at_price' => 499.00,
                'created_at' => '2024-02-07 07:14:40',
                'updated_at' => '2024-02-07 07:14:40',
            ],
            [
                'product_code' => 'OWC',
                'product_name' => 'Web Connect Premium',
                'product_category' => 'Web Connect',
                'product_tag' => json_encode(['web_connect']),
                'bundle_id' => null,
                'image' => 'web_connect_premium.svg',
                'place_type' => 'residential',
                'has_subscription' => 0,
                'content_for_plan' => '<ul><li>Month-to-Month</li><li>UNLIMITED Data</li><li>Free Installation</li><li>Free WIFI-enabled ONT</li></ul>',
                'download_speed' => 40,
                'upload_speed' => 20,
                'contract_period' => 'Month-to-Month',
                'price_PM' => 499.00,
                'compare_at_price' => 699.00,
                'created_at' => '2024-02-07 07:14:40',
                'updated_at' => '2024-02-07 07:14:40',
            ],
            [
                'product_code' => 'OWCA',
                'product_name' => 'Web Connect Air Lite',
                'product_category' => 'Web Connect Air',
                'product_tag' => json_encode(['web_connect_air']),
                'bundle_id' => null,
                'image' => 'web_connect_air_lite.svg',
                'place_type' => 'residential',
                'has_subscription' => 0,
                'content_for_plan' => '<ul><li>Month-to-Month</li><li>UNLIMITED Data</li><li>Free Installation</li><li>Free WIFI-enabled ONT</li></ul>',
                'download_speed' => 20,
                'upload_speed' => 10,
                'contract_period' => 'Month-to-Month',
                'price_PM' => 399.00,
                'compare_at_price' => 499.00,
                'created_at' => '2024-02-07 07:14:40',
                'updated_at' => '2024-02-07 07:14:40',
            ],
            [
                'product_code' => 'OWCA',
                'product_name' => 'Web Connect Extensive',
                'product_category' => 'Web Connect Air',
                'product_tag' => json_encode(['web_connect_air']),
                'bundle_id' => null,
                'image' => 'web_connect_extensive.svg',
                'place_type' => 'residential',
                'has_subscription' => 0,
                'content_for_plan' => '<ul><li>Month-to-Month</li><li>UNLIMITED Data</li><li>Free Installation</li><li>Free WIFI-enabled ONT</li></ul>',
                'download_speed' => 30,
                'upload_speed' => 10,
                'contract_period' => 'Month-to-Month',
                'price_PM' => 499.00,
                'compare_at_price' => null,
                'created_at' => '2024-02-07 07:14:40',
                'updated_at' => '2024-02-07 07:14:40',
            ],
            [
                'product_code' => 'OWS',
                'product_name' => 'Web Stream Lite',
                'product_category' => 'Web Stream',
                'product_tag' => json_encode(['web_stream']),
                'bundle_id' => null,
                'image' => 'web_stream_lite.svg',
                'place_type' => 'residential',
                'has_subscription' => 0,
                'content_for_plan' => '<ul><li>Month-to-Month</li><li>UNLIMITED Data</li><li>Free Installation</li><li>Free WIFI-enabled ONT</li></ul>',
                'download_speed' => 50,
                'upload_speed' => 25,
                'contract_period' => 'Month-to-Month',
                'price_PM' => 599.00,
                'compare_at_price' => 899.00,
                'created_at' => '2024-02-07 07:14:40',
                'updated_at' => '2024-02-07 07:14:40',
            ],
            [
                'product_code' => 'OWS',
                'product_name' => 'Web Stream Extensive',
                'product_category' => 'Web Stream',
                'product_tag' => json_encode(['web_stream']),
                'bundle_id' => null,
                'image' => 'web_stream_extensive.svg',
                'place_type' => 'business',
                'has_subscription' => 0,
                'content_for_plan' => '<ul><li>Month-to-Month</li><li>UNLIMITED Data</li><li>Free Installation</li><li>Free WIFI-enabled ONT</li></ul>',
                'download_speed' => 100,
                'upload_speed' => 50,
                'contract_period' => 'Month-to-Month',
                'price_PM' => 749.00,
                'compare_at_price' => 999.00,
                'created_at' => '2024-02-07 07:14:40',
                'updated_at' => '2024-02-07 07:14:40',
            ],
            [
                'product_code' => 'OWS',
                'product_name' => 'Web Stream Premium',
                'product_category' => 'Web Stream',
                'product_tag' => json_encode(['web_stream', 'SubscriptionFlow']),
                'bundle_id' => null,
                'image' => 'web_stream_premium.svg',
                'place_type' => 'business',
                'has_subscription' => 1,
                'content_for_plan' => '<ul><li>Month-to-Month</li><li>UNLIMITED Data</li><li>Free Installation</li><li>Free WIFI-enabled ONT</li></ul>',
                'download_speed' => 200,
                'upload_speed' => 100,
                'contract_period' => 'Month-to-Month',
                'price_PM' => 899.00,
                'compare_at_price' => 1499.00,
                'created_at' => '2024-02-07 07:14:40',
                'updated_at' => '2024-02-07 07:14:40',
            ],
            [
                'product_code' => 'OWS',
                'product_name' => 'Web Stream Platinum',
                'product_category' => 'Web Stream',
                'product_tag' => json_encode(['web_stream']),
                'bundle_id' => null,
                'image' => 'web_stream_platinum.svg',
                'place_type' => 'business',
                'has_subscription' => 0,
                'content_for_plan' => '<ul><li>Month-to-Month</li><li>UNLIMITED Data</li><li>Free Installation</li><li>Free WIFI-enabled ONT</li></ul>',
                'download_speed' => 300,
                'upload_speed' => 150,
                'contract_period' => 'Month-to-Month',
                'price_PM' => 999.00,
                'compare_at_price' => 1499.00,
                'created_at' => '2024-02-07 07:14:40',
                'updated_at' => '2024-02-07 07:14:40',
            ],
            [
                'product_code' => 'OWS',
                'product_name' => 'Web Stream Diamond',
                'product_category' => 'Web Stream',
                'product_tag' => json_encode(['web_stream']),
                'bundle_id' => null,
                'image' => 'web_stream_diamond.svg',
                'place_type' => 'business',
                'has_subscription' => 0,
                'content_for_plan' => '<ul><li>Month-to-Month</li><li>UNLIMITED Data</li><li>Free Installation</li><li>Free WIFI-enabled ONT</li></ul>',
                'download_speed' => 500,
                'upload_speed' => 250,
                'contract_period' => 'Month-to-Month',
                'price_PM' => 1199.00,
                'compare_at_price' => 1349.00,
                'created_at' => '2024-02-07 07:14:40',
                'updated_at' => '2024-02-07 07:14:40',
            ],
            [
                'product_code' => 'OOCF',
                'product_name' => 'Office Connect Lite',
                'product_category' => 'Office Connect',
                'product_tag' => json_encode(['office_connect', 'SubscriptionFlow']),
                'bundle_id' => null,
                'image' => 'office_connect_lite.svg',
                'place_type' => 'residential',
                'has_subscription' => 1,
                'content_for_plan' => '<ul><li>Month-to-Month</li><li>UNLIMITED Data</li><li>Free Installation</li><li>Free WIFI-enabled ONT</li></ul>',
                'download_speed' => 50,
                'upload_speed' => 50,
                'contract_period' => 'Month-to-Month',
                'price_PM' => 649.00,
                'compare_at_price' => 749.00,
                'created_at' => '2024-02-07 07:14:40',
                'updated_at' => '2024-02-07 07:14:40',
            ],
            [
                'product_code' => 'OOCF',
                'product_name' => 'Office Connect Extensive',
                'product_category' => 'Office Connect',
                'product_tag' => json_encode(['office_connect']),
                'bundle_id' => null,
                'image' => 'office_connect_extensive.svg',
                'place_type' => 'business',
                'has_subscription' => 0,
                'content_for_plan' => '<ul><li>Month-to-Month</li><li>UNLIMITED Data</li><li>Free Installation</li><li>Free WIFI-enabled ONT</li></ul>',
                'download_speed' => 100,
                'upload_speed' => 100,
                'contract_period' => 'Month-to-Month',
                'price_PM' => 799.00,
                'compare_at_price' => 999.00,
                'created_at' => '2024-02-07 07:14:40',
                'updated_at' => '2024-02-07 07:14:40',
            ],
            [
                'product_code' => 'OOCF',
                'product_name' => 'Office Connect Premium',
                'product_category' => 'Office Connect',
                'product_tag' => json_encode(['office_connect']),
                'bundle_id' => null,
                'image' => 'office_connect_premium.svg',
                'place_type' => 'business',
                'has_subscription' => 0,
                'content_for_plan' => '<ul><li>Month-to-Month</li><li>UNLIMITED Data</li><li>Free Installation</li><li>Free WIFI-enabled ONT</li></ul>',
                'download_speed' => 200,
                'upload_speed' => 200,
                'contract_period' => 'Month-to-Month',
                'price_PM' => 949.00,
                'compare_at_price' => 1249.00,
                'created_at' => '2024-02-07 07:14:40',
                'updated_at' => '2024-02-07 07:14:40',
            ],
            [
                'product_code' => 'OOCF',
                'product_name' => 'Office Connect Platinum',
                'product_category' => 'Office Connect',
                'product_tag' => json_encode(['office_connect']),
                'bundle_id' => null,
                'image' => 'office_connect_platinum.svg',
                'place_type' => 'business',
                'has_subscription' => 0,
                'content_for_plan' => '<ul><li>Month-to-Month</li><li>UNLIMITED Data</li><li>Free Installation</li><li>Free WIFI-enabled ONT</li></ul>',
                'download_speed' => 300,
                'upload_speed' => 300,
                'contract_period' => 'Month-to-Month',
                'price_PM' => 999.00,
                'compare_at_price' => 1299.00,
                'created_at' => '2024-02-07 07:14:40',
                'updated_at' => '2024-02-07 07:14:40',
            ],
            [
                'product_code' => 'OOCF',
                'product_name' => 'Office Connect Diamond',
                'product_category' => 'Office Connect',
                'product_tag' => json_encode(['office_connect', 'SubscriptionFlow']),
                'bundle_id' => null,
                'image' => 'office_connect_diamond.svg',
                'place_type' => 'business',
                'has_subscription' => 1,
                'content_for_plan' => '<ul><li>Month-to-Month</li><li>UNLIMITED Data</li><li>Free Installation</li><li>Free WIFI-enabled ONT</li></ul>',
                'download_speed' => 500,
                'upload_speed' => 500,
                'contract_period' => 'Month-to-Month',
                'price_PM' => 1199.00,
                'compare_at_price' => 1499.00,
                'created_at' => '2024-02-07 07:14:40',
                'updated_at' => '2024-02-07 07:14:40',
            ],
            [
                'product_code' => 'OPP',
                'product_name' => 'Prepaid Connect Lite (with 14-day uncapped bundle)',
                'product_category' => 'Prepaid Connect',
                'product_tag' => json_encode(['prepaid_connect']),
                'bundle_id' => '66433fde190869708cfd7f21',
                'image' => 'prepaid_connect_lite.svg',
                'place_type' => 'residential',
                'has_subscription' => 0,
                'content_for_plan' => '<ul><li>With 14-day uncapped bundle</li><li>UNLIMITED Data</li><li>Free Installation</li><li>Free WIFI-enabled ONT</li></ul>',
                'download_speed' => 20,
                'upload_speed' => 10,
                'contract_period' => 'Once Off',
                'price_PM' => 299.00,
                'compare_at_price' => 499.00,
                'created_at' => '2024-02-07 07:14:40',
                'updated_at' => '2024-02-07 07:14:40',
            ],
            [
                'product_code' => 'OPP',
                'product_name' => '7-day uncapped Bundle',
                'product_category' => 'Prepaid Connect',
                'product_tag' => json_encode(['prepaid_connect']),
                'bundle_id' => null,
                'image' => '7_day_uncapped_Bundle.svg',
                'place_type' => 'residential',
                'has_subscription' => 0,
                'content_for_plan' => '<ul><li>7-day uncapped bundle</li><li>UNLIMITED Data</li><li>Free Installation</li><li>Free WIFI-enabled ONT</li></ul>',
                'download_speed' => 20,
                'upload_speed' => 10,
                'contract_period' => 'Once Off',
                'price_PM' => 199.00,
                'compare_at_price' => 299.00,
                'created_at' => '2024-02-07 07:14:40',
                'updated_at' => '2024-02-07 07:14:40',
            ],
            [
                'product_code' => 'OPP',
                'product_name' => '7-Day re-activation bundle',
                'product_category' => 'Prepaid Connect',
                'product_tag' => json_encode(['prepaid_connect']),
                'bundle_id' => null,
                'image' => '7_day_re_activation_bundle.svg',
                'place_type' => 'residential',
                'has_subscription' => 0,
                'content_for_plan' => '<ul><li>7-Day re-activation bundle</li><li>UNLIMITED Data</li><li>Free Installation</li><li>Free WIFI-enabled ONT</li></ul>',
                'download_speed' => 20,
                'upload_speed' => 10,
                'contract_period' => 'Once Off',
                'price_PM' => 249.00,
                'compare_at_price' => 259.00,
                'created_at' => '2024-02-07 07:14:40',
                'updated_at' => '2024-02-07 07:14:40',
            ]
        ];
        foreach ($productMasterData as $value) {
            DB::table('product_master')->insert($value);
        }
    }
}
